# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.12

# some basic checks to delete white space etc...
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-ast
    -   id: name-tests-test
    -   id: debug-statements

# Run black on files and do all the formatting that it likes.
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.7.0
    hooks:
    -   id: black

# Sorts imports automatically in order to tidy them up a bit
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    -   id: isort
        # args: [ "--filter-files" ]

# -   repo: https://github.com/PyCQA/flake8
#     rev: 6.1.0
#     hooks:
#       - id: flake8
#         additional_dependencies:
#           - flake8-black>=0.1.1
# # Have to specify this here because flake8 ignores pyproject.toml sadly.
#         args: ["--max-line-length=88"]

# I have to disable this because the errors are so huge I simply won't be able toc ommit otherwise.
# It would be nice over time to get rid of these errors and bring it back.
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.10.0
#   hooks:
#     - id: mypy
#       # args: ["--disallow-untyped-defs", "--disallow-incomplete-defs", "--ignore-missing-imports"] #, --disallow-untyped-calls]
#       # args: ["--ignore-missing-imports"] #, --disallow-untyped-calls]

# Automatically remove unused (standard library) imports, unused
# variables and useless pass statements.
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place]

# Automatically check, lock and export on commit.
-   repo: https://github.com/python-poetry/poetry
    rev: 1.4.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
# -   repo: github.com/pre-commit/mirrors-mypy
#     rev: v1.4.1

# To do:
# Complain if no type info
# Complain if no docstring
# Mypy
# Coverage
