# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.9
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-ast
    -   id: name-tests-test
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    -   id: isort
        args: [ "--filter-files" ]
# -   repo: https://github.com/PyCQA/flake8
#     rev: 6.1.0
#     hooks:
#       - id: flake8
#         additional_dependencies:
#           - flake8-black>=0.1.1

# -   repo: https://github.com/python-poetry/poetry
#     rev: 1.4.2
#     hooks:
#       - id: poetry-check
      # - id: poetry-lock
      # - id: poetry-export
      #   args: ["-f", "requirements.txt", "-o", "requirements.txt"]
# -   repo: github.com/pre-commit/mirrors-mypy
#     rev: v1.4.1

# To do:
# Complain if no type info
# Complain if no docstring
# Mypy
# Coverage
# poetry
