# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'area.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_area_widget(object):
    def setupUi(self, area_widget):
        area_widget.setObjectName("area_widget")
        area_widget.resize(438, 72)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(area_widget.sizePolicy().hasHeightForWidth())
        area_widget.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(area_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.section_label = QtWidgets.QLabel(area_widget)
        self.section_label.setObjectName("section_label")
        self.horizontalLayout_2.addWidget(self.section_label)
        self.i1_radio_button = QtWidgets.QRadioButton(area_widget)
        self.i1_radio_button.setChecked(True)
        self.i1_radio_button.setObjectName("i1_radio_button")
        self.horizontalLayout_2.addWidget(self.i1_radio_button)
        self.b2_radio_button = QtWidgets.QRadioButton(area_widget)
        self.b2_radio_button.setObjectName("b2_radio_button")
        self.horizontalLayout_2.addWidget(self.b2_radio_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.screen_label = QtWidgets.QLabel(area_widget)
        self.screen_label.setObjectName("screen_label")
        self.horizontalLayout_3.addWidget(self.screen_label)
        self.select_screen_combobox = QtWidgets.QComboBox(area_widget)
        self.select_screen_combobox.setPlaceholderText("")
        self.select_screen_combobox.setObjectName("select_screen_combobox")
        self.horizontalLayout_3.addWidget(self.select_screen_combobox)
        self.jddd_screen_gui_button = QtWidgets.QPushButton(area_widget)
        self.jddd_screen_gui_button.setObjectName("jddd_screen_gui_button")
        self.horizontalLayout_3.addWidget(self.jddd_screen_gui_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(area_widget)
        QtCore.QMetaObject.connectSlotsByName(area_widget)

    def retranslateUi(self, area_widget):
        _translate = QtCore.QCoreApplication.translate
        area_widget.setWindowTitle(_translate("area_widget", "Form"))
        self.section_label.setText(_translate("area_widget", "Section"))
        self.i1_radio_button.setText(_translate("area_widget", "I1"))
        self.b2_radio_button.setText(_translate("area_widget", "B2"))
        self.screen_label.setText(_translate("area_widget", "Screen"))
        self.select_screen_combobox.setToolTip(_translate("area_widget", "The name of the screen to use"))
        self.jddd_screen_gui_button.setToolTip(_translate("area_widget", "Open the corresponding JDDD camera control panel for the selected screen"))
        self.jddd_screen_gui_button.setText(_translate("area_widget", "JDDD..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    area_widget = QtWidgets.QWidget()
    ui = Ui_area_widget()
    ui.setupUi(area_widget)
    area_widget.show()
    sys.exit(app.exec_())
