# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibration_infobox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(455, 332)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.beam_energy_label = QtWidgets.QLabel(Form)
        self.beam_energy_label.setObjectName("beam_energy_label")
        self.gridLayout.addWidget(self.beam_energy_label, 0, 0, 1, 1)
        self.beam_energy_value_label = QtWidgets.QLabel(Form)
        self.beam_energy_value_label.setText("")
        self.beam_energy_value_label.setObjectName("beam_energy_value_label")
        self.gridLayout.addWidget(self.beam_energy_value_label, 0, 1, 1, 1)
        self.tds_frequency_label = QtWidgets.QLabel(Form)
        self.tds_frequency_label.setObjectName("tds_frequency_label")
        self.gridLayout.addWidget(self.tds_frequency_label, 1, 0, 1, 1)
        self.tds_frequency_value_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.tds_frequency_value_label.setFont(font)
        self.tds_frequency_value_label.setObjectName("tds_frequency_value_label")
        self.gridLayout.addWidget(self.tds_frequency_value_label, 1, 1, 1, 1)
        self.screen_label = QtWidgets.QLabel(Form)
        self.screen_label.setObjectName("screen_label")
        self.gridLayout.addWidget(self.screen_label, 2, 0, 1, 1)
        self.screen_value_label = QtWidgets.QLabel(Form)
        self.screen_value_label.setText("")
        self.screen_value_label.setObjectName("screen_value_label")
        self.gridLayout.addWidget(self.screen_value_label, 2, 1, 1, 1)
        self.screen_position_label = QtWidgets.QLabel(Form)
        self.screen_position_label.setObjectName("screen_position_label")
        self.gridLayout.addWidget(self.screen_position_label, 3, 0, 1, 1)
        self.screen_position_value_label = QtWidgets.QLabel(Form)
        self.screen_position_value_label.setText("")
        self.screen_position_value_label.setObjectName("screen_position_value_label")
        self.gridLayout.addWidget(self.screen_position_value_label, 3, 1, 1, 1)
        self.pixel_size_label = QtWidgets.QLabel(Form)
        self.pixel_size_label.setObjectName("pixel_size_label")
        self.gridLayout.addWidget(self.pixel_size_label, 4, 0, 1, 1)
        self.pixel_size_value_label = QtWidgets.QLabel(Form)
        self.pixel_size_value_label.setText("")
        self.pixel_size_value_label.setObjectName("pixel_size_value_label")
        self.gridLayout.addWidget(self.pixel_size_value_label, 4, 1, 1, 1)
        self.r12_streaking_label = QtWidgets.QLabel(Form)
        self.r12_streaking_label.setObjectName("r12_streaking_label")
        self.gridLayout.addWidget(self.r12_streaking_label, 5, 0, 1, 1)
        self.r12_streaking_value_label = QtWidgets.QLabel(Form)
        self.r12_streaking_value_label.setText("")
        self.r12_streaking_value_label.setObjectName("r12_streaking_value_label")
        self.gridLayout.addWidget(self.r12_streaking_value_label, 5, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.beam_energy_label.setText(_translate("Form", "Beam Energy:"))
        self.tds_frequency_label.setText(_translate("Form", "TDS Frequency:"))
        self.tds_frequency_value_label.setText(_translate("Form", "3 GHz"))
        self.screen_label.setText(_translate("Form", "Screen:"))
        self.screen_position_label.setText(_translate("Form", "Screen Position:"))
        self.pixel_size_label.setText(_translate("Form", "Pixel Size:"))
        self.r12_streaking_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-style:italic;\">R</span><span style=\" vertical-align:sub;\">34</span>:</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
