# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.area_control = AreaControl(self.centralwidget)
        self.area_control.setObjectName("area_control")
        self.gridLayout_4.addWidget(self.area_control, 0, 0, 1, 1)
        self.plot_stack = QtWidgets.QStackedWidget(self.centralwidget)
        self.plot_stack.setObjectName("plot_stack")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.i1_calibration_graphics = GraphicsLayoutWidget(self.page_3)
        self.i1_calibration_graphics.setObjectName("i1_calibration_graphics")
        self.gridLayout_3.addWidget(self.i1_calibration_graphics, 0, 0, 1, 1)
        self.i1_pscan_graphics = GraphicsLayoutWidget(self.page_3)
        self.i1_pscan_graphics.setObjectName("i1_pscan_graphics")
        self.gridLayout_3.addWidget(self.i1_pscan_graphics, 1, 0, 1, 1)
        self.plot_stack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.b2_calibration_graphics = GraphicsLayoutWidget(self.page_4)
        self.b2_calibration_graphics.setGeometry(QtCore.QRect(50, 11, 257, 169))
        self.b2_calibration_graphics.setObjectName("b2_calibration_graphics")
        self.b2_pscan_graphics = GraphicsLayoutWidget(self.page_4)
        self.b2_pscan_graphics.setGeometry(QtCore.QRect(50, 190, 257, 168))
        self.b2_pscan_graphics.setObjectName("b2_pscan_graphics")
        self.plot_stack.addWidget(self.page_4)
        self.gridLayout_4.addWidget(self.plot_stack, 0, 1, 1, 1)
        self.table_stack = QtWidgets.QStackedWidget(self.centralwidget)
        self.table_stack.setObjectName("table_stack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.i1_calibration_table_view = QtWidgets.QTableView(self.page)
        self.i1_calibration_table_view.setObjectName("i1_calibration_table_view")
        self.gridLayout.addWidget(self.i1_calibration_table_view, 0, 0, 1, 1)
        self.table_stack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.b2_calibration_table_view = QtWidgets.QTableView(self.page_2)
        self.b2_calibration_table_view.setObjectName("b2_calibration_table_view")
        self.gridLayout_2.addWidget(self.b2_calibration_table_view, 0, 0, 1, 1)
        self.table_stack.addWidget(self.page_2)
        self.gridLayout_4.addWidget(self.table_stack, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Calibration = QtWidgets.QAction(MainWindow)
        self.actionLoad_Calibration.setObjectName("actionLoad_Calibration")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionLoad_Calibration)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.plot_stack.setCurrentIndex(1)
        self.table_stack.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Calibration.setText(
            _translate("MainWindow", "Load Calibration...")
        )
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


from pyqtgraph import GraphicsLayoutWidget

from esme.gui.widgets.area import AreaControl

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
