# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dispersion.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 615)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(240, 40, 120, 80))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(300, 270, 253, 211))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.vlow_spinner = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.vlow_spinner.setObjectName("vlow_spinner")
        self.gridLayout.addWidget(self.vlow_spinner, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.vhigh_spinner = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.vhigh_spinner.setObjectName("vhigh_spinner")
        self.gridLayout.addWidget(self.vhigh_spinner, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.expected_dispersion_label = QtWidgets.QLabel(self.groupBox)
        self.expected_dispersion_label.setObjectName("expected_dispersion_label")
        self.gridLayout.addWidget(self.expected_dispersion_label, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 2)
        self.measured_dispersion_label = QtWidgets.QLabel(self.groupBox)
        self.measured_dispersion_label.setObjectName("measured_dispersion_label")
        self.gridLayout.addWidget(self.measured_dispersion_label, 4, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 2, 1, 1)
        self.rf_station_label = QtWidgets.QLabel(self.groupBox)
        self.rf_station_label.setObjectName("rf_station_label")
        self.gridLayout.addWidget(self.rf_station_label, 0, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Measurement"))
        self.label_3.setText(_translate("Form", "RF Station"))
        self.label.setText(_translate("Form", "Lower Voltage / MV"))
        self.label_2.setText(_translate("Form", "Upper Voltage / MV"))
        self.label_4.setText(_translate("Form", "Expected Dispersion"))
        self.expected_dispersion_label.setText(_translate("Form", "TextLabel"))
        self.label_6.setText(_translate("Form", "Measured Dispersion"))
        self.measured_dispersion_label.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "Start Measurement"))
        self.pushButton_2.setText(_translate("Form", "Close"))
        self.rf_station_label.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
