# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imaging.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_imaging_widget(object):
    def setupUi(self, imaging_widget):
        imaging_widget.setObjectName("imaging_widget")
        imaging_widget.resize(780, 661)
        self.verticalLayout = QtWidgets.QVBoxLayout(imaging_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.screen_display_widget = ScreenWidget(imaging_widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.screen_display_widget.sizePolicy().hasHeightForWidth()
        )
        self.screen_display_widget.setSizePolicy(sizePolicy)
        self.screen_display_widget.setObjectName("screen_display_widget")
        self.verticalLayout.addWidget(self.screen_display_widget)
        self.groupBox = QtWidgets.QGroupBox(imaging_widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.take_background_button = QtWidgets.QPushButton(self.groupBox)
        self.take_background_button.setObjectName("take_background_button")
        self.gridLayout_6.addWidget(self.take_background_button, 1, 0, 1, 1)
        self.send_to_logbook_button = QtWidgets.QPushButton(self.groupBox)
        self.send_to_logbook_button.setStyleSheet("QPushButton { color: blue; }")
        self.send_to_logbook_button.setObjectName("send_to_logbook_button")
        self.gridLayout_6.addWidget(self.send_to_logbook_button, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 0, 2, 2, 1)
        self.current_profile_button = QtWidgets.QPushButton(self.groupBox)
        self.current_profile_button.setEnabled(False)
        self.current_profile_button.setObjectName("current_profile_button")
        self.gridLayout_6.addWidget(self.current_profile_button, 0, 3, 1, 1)
        self.nbg_images_acquired_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.nbg_images_acquired_label.setFont(font)
        self.nbg_images_acquired_label.setObjectName("nbg_images_acquired_label")
        self.gridLayout_6.addWidget(self.nbg_images_acquired_label, 0, 1, 1, 1)
        self.subtract_bg_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.subtract_bg_checkbox.setEnabled(True)
        self.subtract_bg_checkbox.setObjectName("subtract_bg_checkbox")
        self.gridLayout_6.addWidget(self.subtract_bg_checkbox, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(imaging_widget)
        QtCore.QMetaObject.connectSlotsByName(imaging_widget)

    def retranslateUi(self, imaging_widget):
        _translate = QtCore.QCoreApplication.translate
        imaging_widget.setWindowTitle(_translate("imaging_widget", "Form"))
        self.groupBox.setTitle(_translate("imaging_widget", "Measurements"))
        self.take_background_button.setText(
            _translate("imaging_widget", "Accumulate Background")
        )
        self.send_to_logbook_button.setText(
            _translate("imaging_widget", "XFEL e-Logbook...")
        )
        self.current_profile_button.setText(
            _translate("imaging_widget", "Current Profile")
        )
        self.nbg_images_acquired_label.setText(
            _translate("imaging_widget", "Background Images: 0")
        )
        self.subtract_bg_checkbox.setText(
            _translate("imaging_widget", "Subtract background")
        )
        self.pushButton.setText(_translate("imaging_widget", "Slice Emittance"))


from esme.gui.widgets.screen import ScreenWidget

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    imaging_widget = QtWidgets.QWidget()
    ui = Ui_imaging_widget()
    ui.setupUi(imaging_widget)
    imaging_widget.show()
    sys.exit(app.exec_())
