# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lps.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hires_mainwindow(object):
    def setupUi(self, hires_mainwindow):
        hires_mainwindow.setObjectName("hires_mainwindow")
        hires_mainwindow.resize(800, 604)
        self.centralwidget = QtWidgets.QWidget(hires_mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dispersion_pixel_size_plot_widget = GraphicsLayoutWidget(self.centralwidget)
        self.dispersion_pixel_size_plot_widget.setMinimumSize(QtCore.QSize(289, 170))
        self.dispersion_pixel_size_plot_widget.setObjectName("dispersion_pixel_size_plot_widget")
        self.verticalLayout_2.addWidget(self.dispersion_pixel_size_plot_widget)
        self.voltage_pixel_size_plot_widget = GraphicsLayoutWidget(self.centralwidget)
        self.voltage_pixel_size_plot_widget.setMinimumSize(QtCore.QSize(289, 169))
        self.voltage_pixel_size_plot_widget.setObjectName("voltage_pixel_size_plot_widget")
        self.verticalLayout_2.addWidget(self.voltage_pixel_size_plot_widget)
        self.beta_pixel_size_plot = GraphicsLayoutWidget(self.centralwidget)
        self.beta_pixel_size_plot.setMinimumSize(QtCore.QSize(289, 169))
        self.beta_pixel_size_plot.setObjectName("beta_pixel_size_plot")
        self.verticalLayout_2.addWidget(self.beta_pixel_size_plot)
        self.image_plot = GraphicsLayoutWidget(self.centralwidget)
        self.image_plot.setMinimumSize(QtCore.QSize(289, 170))
        self.image_plot.setObjectName("image_plot")
        self.verticalLayout_2.addWidget(self.image_plot)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_log_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.info_log_box.setMinimumSize(QtCore.QSize(256, 0))
        self.info_log_box.setMaximumSize(QtCore.QSize(500, 16777215))
        self.info_log_box.setObjectName("info_log_box")
        self.verticalLayout.addWidget(self.info_log_box)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(251, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(500, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.scanner_panel = ScannerControl(self.groupBox)
        self.scanner_panel.setObjectName("scanner_panel")
        self.gridLayout.addWidget(self.scanner_panel, 0, 0, 1, 2)
        self.tds_panel = TDSControl(self.groupBox)
        self.tds_panel.setObjectName("tds_panel")
        self.gridLayout.addWidget(self.tds_panel, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        hires_mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(hires_mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        hires_mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(hires_mainwindow)
        self.statusbar.setObjectName("statusbar")
        hires_mainwindow.setStatusBar(self.statusbar)

        self.retranslateUi(hires_mainwindow)
        QtCore.QMetaObject.connectSlotsByName(hires_mainwindow)

    def retranslateUi(self, hires_mainwindow):
        _translate = QtCore.QCoreApplication.translate
        hires_mainwindow.setWindowTitle(_translate("hires_mainwindow", "MainWindow"))
        self.groupBox.setTitle(_translate("hires_mainwindow", "Controls"))
from esme.gui.scannerpanel import ScannerControl
from esme.gui.tds import TDSControl
from pyqtgraph import GraphicsLayoutWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hires_mainwindow = QtWidgets.QMainWindow()
    ui = Ui_hires_mainwindow()
    ui.setupUi(hires_mainwindow)
    hires_mainwindow.show()
    sys.exit(app.exec_())
