# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_tdsfriend_mainwindow(object):
    def setupUi(self, tdsfriend_mainwindow):
        tdsfriend_mainwindow.setObjectName("tdsfriend_mainwindow")
        tdsfriend_mainwindow.resize(2100, 1350)
        tdsfriend_mainwindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(tdsfriend_mainwindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.maintab = QtWidgets.QWidget()
        self.maintab.setObjectName("maintab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.maintab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.controls_group_box = QtWidgets.QGroupBox(self.maintab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.controls_group_box.sizePolicy().hasHeightForWidth()
        )
        self.controls_group_box.setSizePolicy(sizePolicy)
        self.controls_group_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.controls_group_box.setObjectName("controls_group_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.controls_group_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.area = AreaControl(self.controls_group_box)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.area.sizePolicy().hasHeightForWidth())
        self.area.setSizePolicy(sizePolicy)
        self.area.setObjectName("area")
        self.gridLayout_2.addWidget(self.area, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.controls_group_box)
        self.groupBox_3 = QtWidgets.QGroupBox(self.maintab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.special_bunch_panel = SpecialBunchMidLayerPanel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.special_bunch_panel.sizePolicy().hasHeightForWidth()
        )
        self.special_bunch_panel.setSizePolicy(sizePolicy)
        self.special_bunch_panel.setObjectName("special_bunch_panel")
        self.verticalLayout.addWidget(self.special_bunch_panel)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.maintab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tds_panel = TDSControl(self.groupBox_2)
        self.tds_panel.setObjectName("tds_panel")
        self.gridLayout_4.addWidget(self.tds_panel, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.maintab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.machine_state_widget = LPSStateWatcher(self.groupBox_4)
        self.machine_state_widget.setObjectName("machine_state_widget")
        self.verticalLayout_2.addWidget(self.machine_state_widget)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.imaging_widget = ImagingControlWidget(self.maintab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.imaging_widget.sizePolicy().hasHeightForWidth()
        )
        self.imaging_widget.setSizePolicy(sizePolicy)
        self.imaging_widget.setObjectName("imaging_widget")
        self.gridLayout_3.addWidget(self.imaging_widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.maintab, "")
        self.logtab = QtWidgets.QWidget()
        self.logtab.setObjectName("logtab")
        self.gridLayout = QtWidgets.QGridLayout(self.logtab)
        self.gridLayout.setObjectName("gridLayout")
        self.measurement_log_browser = QtWidgets.QTextBrowser(self.logtab)
        self.measurement_log_browser.setObjectName("measurement_log_browser")
        self.gridLayout.addWidget(self.measurement_log_browser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.logtab, "")
        self.gridLayout_9.addWidget(self.tabWidget, 0, 0, 1, 1)
        tdsfriend_mainwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tdsfriend_mainwindow)
        self.statusbar.setObjectName("statusbar")
        tdsfriend_mainwindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(tdsfriend_mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2100, 24))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuExternal = QtWidgets.QMenu(self.menubar)
        self.menuExternal.setObjectName("menuExternal")
        self.menuExpert = QtWidgets.QMenu(self.menuExternal)
        self.menuExpert.setObjectName("menuExpert")
        self.menuI1_3 = QtWidgets.QMenu(self.menuExpert)
        self.menuI1_3.setObjectName("menuI1_3")
        self.menuB2_3 = QtWidgets.QMenu(self.menuExpert)
        self.menuB2_3.setObjectName("menuB2_3")
        tdsfriend_mainwindow.setMenuBar(self.menubar)
        self.action_close = QtWidgets.QAction(tdsfriend_mainwindow)
        self.action_close.setObjectName("action_close")
        self.action_print_to_logbook = QtWidgets.QAction(tdsfriend_mainwindow)
        self.action_print_to_logbook.setObjectName("action_print_to_logbook")
        self.actionBunch_Length = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionBunch_Length.setObjectName("actionBunch_Length")
        self.actionLongitudinal_Phase_Space = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionLongitudinal_Phase_Space.setObjectName(
            "actionLongitudinal_Phase_Space"
        )
        self.actionEmittance = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionEmittance.setObjectName("actionEmittance")
        self.actionEmail_Maintainer = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionEmail_Maintainer.setObjectName("actionEmail_Maintainer")
        self.actionTDS = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionTDS.setObjectName("actionTDS")
        self.actionCamera_Status = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionCamera_Status.setObjectName("actionCamera_Status")
        self.actionSBM = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionSBM.setObjectName("actionSBM")
        self.actionLLRF = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionLLRF.setObjectName("actionLLRF")
        self.actionSBM_2 = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionSBM_2.setObjectName("actionSBM_2")
        self.actionLLRF_2 = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionLLRF_2.setObjectName("actionLLRF_2")
        self.actionImage_Analysis_Server = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionImage_Analysis_Server.setObjectName("actionImage_Analysis_Server")
        self.actionImage_Analysis_Server_2 = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionImage_Analysis_Server_2.setObjectName(
            "actionImage_Analysis_Server_2"
        )
        self.actionLLRLF = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionLLRLF.setObjectName("actionLLRLF")
        self.actionSBM_3 = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionSBM_3.setObjectName("actionSBM_3")
        self.actionLLRF_3 = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionLLRF_3.setObjectName("actionLLRF_3")
        self.actionSBM_4 = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionSBM_4.setObjectName("actionSBM_4")
        self.actionLLRF_4 = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionLLRF_4.setObjectName("actionLLRF_4")
        self.actionSpecial_Bunch_Midlayer = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionSpecial_Bunch_Midlayer.setObjectName("actionSpecial_Bunch_Midlayer")
        self.actionLLRF_5 = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionLLRF_5.setObjectName("actionLLRF_5")
        self.actionSpecial_Bunch_Midlayer_2 = QtWidgets.QAction(tdsfriend_mainwindow)
        self.actionSpecial_Bunch_Midlayer_2.setObjectName(
            "actionSpecial_Bunch_Midlayer_2"
        )
        self.menuMenu.addAction(self.action_print_to_logbook)
        self.menuMenu.addAction(self.action_close)
        self.menuI1_3.addAction(self.actionLLRF_4)
        self.menuI1_3.addAction(self.actionSpecial_Bunch_Midlayer)
        self.menuB2_3.addAction(self.actionLLRF_5)
        self.menuB2_3.addAction(self.actionSpecial_Bunch_Midlayer_2)
        self.menuExpert.addAction(self.actionImage_Analysis_Server_2)
        self.menuExpert.addAction(self.menuI1_3.menuAction())
        self.menuExpert.addAction(self.menuB2_3.menuAction())
        self.menuExternal.addAction(self.actionTDS)
        self.menuExternal.addAction(self.actionCamera_Status)
        self.menuExternal.addAction(self.menuExpert.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuExternal.menuAction())

        self.retranslateUi(tdsfriend_mainwindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tdsfriend_mainwindow)

    def retranslateUi(self, tdsfriend_mainwindow):
        _translate = QtCore.QCoreApplication.translate
        tdsfriend_mainwindow.setWindowTitle(
            _translate("tdsfriend_mainwindow", "Diagnostic Sections Utility")
        )
        self.controls_group_box.setTitle(
            _translate("tdsfriend_mainwindow", "Diagnostic Area")
        )
        self.groupBox_3.setTitle(
            _translate("tdsfriend_mainwindow", "Special Bunch Midlayer")
        )
        self.groupBox_2.setTitle(
            _translate("tdsfriend_mainwindow", "Transverse Deflecting Structure")
        )
        self.groupBox_4.setTitle(_translate("tdsfriend_mainwindow", "Machine State"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.maintab),
            _translate("tdsfriend_mainwindow", "Main"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.logtab),
            _translate("tdsfriend_mainwindow", "Log"),
        )
        self.menuMenu.setTitle(_translate("tdsfriend_mainwindow", "Menu"))
        self.menuExternal.setTitle(_translate("tdsfriend_mainwindow", "External"))
        self.menuExpert.setTitle(_translate("tdsfriend_mainwindow", "Expert"))
        self.menuI1_3.setTitle(_translate("tdsfriend_mainwindow", "I1"))
        self.menuB2_3.setTitle(_translate("tdsfriend_mainwindow", "B2"))
        self.action_close.setText(_translate("tdsfriend_mainwindow", "Close"))
        self.action_close.setShortcut(_translate("tdsfriend_mainwindow", "Ctrl+Q"))
        self.action_print_to_logbook.setText(
            _translate("tdsfriend_mainwindow", "Print to Logbook")
        )
        self.action_print_to_logbook.setShortcut(
            _translate("tdsfriend_mainwindow", "Ctrl+P")
        )
        self.actionBunch_Length.setText(
            _translate("tdsfriend_mainwindow", "Bunch Length...")
        )
        self.actionLongitudinal_Phase_Space.setText(
            _translate("tdsfriend_mainwindow", "Longitudinal Phase Space...")
        )
        self.actionEmittance.setText(_translate("tdsfriend_mainwindow", "Emittance..."))
        self.actionEmail_Maintainer.setText(
            _translate("tdsfriend_mainwindow", "Email Maintainer")
        )
        self.actionTDS.setText(_translate("tdsfriend_mainwindow", "Pattern Builder"))
        self.actionCamera_Status.setText(
            _translate("tdsfriend_mainwindow", "Camera Status")
        )
        self.actionSBM.setText(_translate("tdsfriend_mainwindow", "SBM"))
        self.actionLLRF.setText(_translate("tdsfriend_mainwindow", "LLRF"))
        self.actionSBM_2.setText(_translate("tdsfriend_mainwindow", "SBM"))
        self.actionLLRF_2.setText(_translate("tdsfriend_mainwindow", "LLRF"))
        self.actionImage_Analysis_Server.setText(
            _translate("tdsfriend_mainwindow", "Image Analysis Server")
        )
        self.actionImage_Analysis_Server_2.setText(
            _translate("tdsfriend_mainwindow", "Image Analysis Server")
        )
        self.actionLLRLF.setText(_translate("tdsfriend_mainwindow", "LLRLF"))
        self.actionSBM_3.setText(_translate("tdsfriend_mainwindow", "SBM"))
        self.actionLLRF_3.setText(_translate("tdsfriend_mainwindow", "LLRF"))
        self.actionSBM_4.setText(_translate("tdsfriend_mainwindow", "SBM"))
        self.actionLLRF_4.setText(_translate("tdsfriend_mainwindow", "LLRF"))
        self.actionSpecial_Bunch_Midlayer.setText(
            _translate("tdsfriend_mainwindow", "Special Bunch Midlayer")
        )
        self.actionLLRF_5.setText(_translate("tdsfriend_mainwindow", "LLRF"))
        self.actionSpecial_Bunch_Midlayer_2.setText(
            _translate("tdsfriend_mainwindow", "Special Bunch Midlayer")
        )


from esme.gui.widgets.area import AreaControl
from esme.gui.widgets.imaging import ImagingControlWidget
from esme.gui.widgets.sbunchpanel import SpecialBunchMidLayerPanel
from esme.gui.widgets.status import LPSStateWatcher
from esme.gui.widgets.tds import TDSControl

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    tdsfriend_mainwindow = QtWidgets.QMainWindow()
    ui = Ui_tdsfriend_mainwindow()
    ui.setupUi(tdsfriend_mainwindow)
    tdsfriend_mainwindow.show()
    sys.exit(app.exec_())
