# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanner_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(587, 640)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.quad_sleep_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.quad_sleep_spinbox.setObjectName("quad_sleep_spinbox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.quad_sleep_spinbox)
        self.tds_amplitude_wait_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.tds_amplitude_wait_spinbox.setObjectName("tds_amplitude_wait_spinbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tds_amplitude_wait_spinbox)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.beam_on_wait_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.beam_on_wait_spinbox.setObjectName("beam_on_wait_spinbox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.beam_on_wait_spinbox)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.tds_on_wait_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.tds_on_wait_spinbox.setObjectName("tds_on_wait_spinbox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tds_on_wait_spinbox)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.output_directory_lineedit = QtWidgets.QLineEdit(Dialog)
        self.output_directory_lineedit.setObjectName("output_directory_lineedit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.output_directory_lineedit)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.pixel_size_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.pixel_size_spinbox.setObjectName("pixel_size_spinbox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pixel_size_spinbox)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sleep after TDS Amplitude Set"))
        self.label_2.setText(_translate("Dialog", "Sleep after Quad Set"))
        self.label_3.setText(_translate("Dialog", "Beam On Wait"))
        self.label_4.setText(_translate("Dialog", "TDS On Wait"))
        self.label_5.setText(_translate("Dialog", "Data Directory"))
        self.label_6.setText(_translate("Dialog", "Pixel Size / m"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
