# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slicer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_slice_analysis_gui(object):
    def setupUi(self, slice_analysis_gui):
        slice_analysis_gui.setObjectName("slice_analysis_gui")
        slice_analysis_gui.resize(1017, 629)
        self.gridLayout_2 = QtWidgets.QGridLayout(slice_analysis_gui)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(slice_analysis_gui)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pick_image_from_file_spinner = QtWidgets.QSpinBox(self.groupBox)
        self.pick_image_from_file_spinner.setObjectName("pick_image_from_file_spinner")
        self.horizontalLayout.addWidget(self.pick_image_from_file_spinner)
        self.load_image_from_file_button = QtWidgets.QPushButton(self.groupBox)
        self.load_image_from_file_button.setObjectName("load_image_from_file_button")
        self.horizontalLayout.addWidget(self.load_image_from_file_button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.send_to_logbook_button = QtWidgets.QPushButton(self.groupBox)
        self.send_to_logbook_button.setObjectName("send_to_logbook_button")
        self.gridLayout.addWidget(self.send_to_logbook_button, 2, 0, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(self.groupBox)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 2, 1, 1, 1)
        self.get_image_button = QtWidgets.QPushButton(self.groupBox)
        self.get_image_button.setObjectName("get_image_button")
        self.gridLayout.addWidget(self.get_image_button, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.centroid_profile_graphics = GraphicsLayoutWidget(slice_analysis_gui)
        self.centroid_profile_graphics.setObjectName("centroid_profile_graphics")
        self.gridLayout_2.addWidget(self.centroid_profile_graphics, 0, 1, 2, 1)
        self.lps_graphics = GraphicsLayoutWidget(slice_analysis_gui)
        self.lps_graphics.setObjectName("lps_graphics")
        self.gridLayout_2.addWidget(self.lps_graphics, 0, 0, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(slice_analysis_gui)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.beta_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.beta_spinbox.setObjectName("beta_spinbox")
        self.gridLayout_3.addWidget(self.beta_spinbox, 8, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 9, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 6, 0, 1, 1)
        self.screen_name_label = QtWidgets.QLabel(self.groupBox_2)
        self.screen_name_label.setText("")
        self.screen_name_label.setObjectName("screen_name_label")
        self.gridLayout_3.addWidget(self.screen_name_label, 0, 1, 1, 1)
        self.voltage_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.voltage_spinbox.setObjectName("voltage_spinbox")
        self.gridLayout_3.addWidget(self.voltage_spinbox, 7, 1, 1, 1)
        self.timecal_spinner = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.timecal_spinner.setObjectName("timecal_spinner")
        self.gridLayout_3.addWidget(self.timecal_spinner, 3, 1, 1, 1)
        self.energy_cal_spinner = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.energy_cal_spinner.setObjectName("energy_cal_spinner")
        self.gridLayout_3.addWidget(self.energy_cal_spinner, 6, 1, 1, 1)
        self.screen_resolution_spinner = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.screen_resolution_spinner.setObjectName("screen_resolution_spinner")
        self.gridLayout_3.addWidget(self.screen_resolution_spinner, 10, 1, 1, 1)
        self.beam_energy_spinner = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.beam_energy_spinner.setObjectName("beam_energy_spinner")
        self.gridLayout_3.addWidget(self.beam_energy_spinner, 9, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 10, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_3.addWidget(self.doubleSpinBox_2, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 1, 1, 1)

        self.retranslateUi(slice_analysis_gui)
        QtCore.QMetaObject.connectSlotsByName(slice_analysis_gui)

    def retranslateUi(self, slice_analysis_gui):
        _translate = QtCore.QCoreApplication.translate
        slice_analysis_gui.setWindowTitle(_translate("slice_analysis_gui", "Form"))
        self.groupBox.setTitle(_translate("slice_analysis_gui", "Control"))
        self.label.setText(_translate("slice_analysis_gui", "Image Number"))
        self.load_image_from_file_button.setText(
            _translate("slice_analysis_gui", "Load Image From File...")
        )
        self.send_to_logbook_button.setText(
            _translate("slice_analysis_gui", "Send to XFEL e-Logbook")
        )
        self.cancel_button.setText(_translate("slice_analysis_gui", "Cancel"))
        self.get_image_button.setText(
            _translate("slice_analysis_gui", "Get Image From Screen")
        )
        self.groupBox_2.setTitle(
            _translate("slice_analysis_gui", "Measurement Parameters")
        )
        self.label_4.setText(_translate("slice_analysis_gui", "TDS Voltage / MV"))
        self.label_6.setText(_translate("slice_analysis_gui", "Beam Energy / MeV"))
        self.label_7.setText(_translate("slice_analysis_gui", "Pixel Size x / µm"))
        self.label_2.setText(
            _translate("slice_analysis_gui", "Time Calibration / µmps")
        )
        self.label_3.setText(
            _translate("slice_analysis_gui", "Energy Calibration / MeV m⁻¹")
        )
        self.label_8.setText(_translate("slice_analysis_gui", "Screen"))
        self.label_5.setText(_translate("slice_analysis_gui", "Beta / m"))
        self.label_9.setText(_translate("slice_analysis_gui", "Screen Resolution / µm"))
        self.label_10.setText(_translate("slice_analysis_gui", "Pixel Size y / µm"))


from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    slice_analysis_gui = QtWidgets.QWidget()
    ui = Ui_slice_analysis_gui()
    ui.setupUi(slice_analysis_gui)
    slice_analysis_gui.show()
    sys.exit(app.exec_())
