# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'target.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Target(object):
    def setupUi(self, Target):
        Target.setObjectName("Target")
        Target.resize(388, 99)
        self.gridLayout = QtWidgets.QGridLayout(Target)
        self.gridLayout.setObjectName("gridLayout")
        self.go_to_dump_button = QtWidgets.QPushButton(Target)
        self.go_to_dump_button.setObjectName("go_to_dump_button")
        self.gridLayout.addWidget(self.go_to_dump_button, 0, 0, 1, 1)
        self.go_straight_button = QtWidgets.QPushButton(Target)
        self.go_straight_button.setObjectName("go_straight_button")
        self.gridLayout.addWidget(self.go_straight_button, 0, 1, 1, 3)
        self.enable_dump_control_checkbox = QtWidgets.QCheckBox(Target)
        self.enable_dump_control_checkbox.setObjectName("enable_dump_control_checkbox")
        self.gridLayout.addWidget(self.enable_dump_control_checkbox, 0, 4, 1, 1)
        self.line = QtWidgets.QFrame(Target)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 5)
        self.optics_combo_box = QtWidgets.QComboBox(Target)
        self.optics_combo_box.setEnabled(False)
        self.optics_combo_box.setObjectName("optics_combo_box")
        self.gridLayout.addWidget(self.optics_combo_box, 2, 0, 1, 2)
        self.set_optics_button = QtWidgets.QPushButton(Target)
        self.set_optics_button.setEnabled(False)
        self.set_optics_button.setObjectName("set_optics_button")
        self.gridLayout.addWidget(self.set_optics_button, 2, 2, 1, 1)
        self.set_and_cycle_optics_button = QtWidgets.QPushButton(Target)
        self.set_and_cycle_optics_button.setEnabled(False)
        self.set_and_cycle_optics_button.setObjectName("set_and_cycle_optics_button")
        self.gridLayout.addWidget(self.set_and_cycle_optics_button, 2, 3, 1, 2)

        self.retranslateUi(Target)
        QtCore.QMetaObject.connectSlotsByName(Target)

    def retranslateUi(self, Target):
        _translate = QtCore.QCoreApplication.translate
        Target.setWindowTitle(_translate("Target", "Form"))
        self.go_to_dump_button.setText(_translate("Target", "Go to I1D..."))
        self.go_straight_button.setText(
            _translate("Target", "Undo I1D and go to TLD...")
        )
        self.enable_dump_control_checkbox.setText(_translate("Target", "Enable "))
        self.set_optics_button.setText(_translate("Target", "Set"))
        self.set_and_cycle_optics_button.setText(_translate("Target", "Set && Cycle"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Target = QtWidgets.QWidget()
    ui = Ui_Target()
    ui.setupUi(Target)
    Target.show()
    sys.exit(app.exec_())
