# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'target.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Target(object):
    def setupUi(self, Target):
        Target.setObjectName("Target")
        Target.resize(368, 44)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Target)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.go_to_dump_button = QtWidgets.QPushButton(Target)
        self.go_to_dump_button.setObjectName("go_to_dump_button")
        self.horizontalLayout.addWidget(self.go_to_dump_button)
        self.go_straight_button = QtWidgets.QPushButton(Target)
        self.go_straight_button.setObjectName("go_straight_button")
        self.horizontalLayout.addWidget(self.go_straight_button)
        self.enable_panel_checkbox = QtWidgets.QCheckBox(Target)
        self.enable_panel_checkbox.setObjectName("enable_panel_checkbox")
        self.horizontalLayout.addWidget(self.enable_panel_checkbox)

        self.retranslateUi(Target)
        QtCore.QMetaObject.connectSlotsByName(Target)

    def retranslateUi(self, Target):
        _translate = QtCore.QCoreApplication.translate
        Target.setWindowTitle(_translate("Target", "Form"))
        self.go_to_dump_button.setText(_translate("Target", "Go to I1D"))
        self.go_straight_button.setText(_translate("Target", "Undo I1D and go to TLD"))
        self.enable_panel_checkbox.setText(_translate("Target", "Enable "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Target = QtWidgets.QWidget()
    ui = Ui_Target()
    ui.setupUi(Target)
    Target.show()
    sys.exit(app.exec_())
