# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tds.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tds_control_panel(object):
    def setupUi(self, tds_control_panel):
        tds_control_panel.setObjectName("tds_control_panel")
        tds_control_panel.resize(351, 138)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tds_control_panel.sizePolicy().hasHeightForWidth())
        tds_control_panel.setSizePolicy(sizePolicy)
        tds_control_panel.setMinimumSize(QtCore.QSize(0, 138))
        tds_control_panel.setMaximumSize(QtCore.QSize(351, 138))
        self.gridLayout = QtWidgets.QGridLayout(tds_control_panel)
        self.gridLayout.setObjectName("gridLayout")
        self.phase_label_2 = QtWidgets.QLabel(tds_control_panel)
        self.phase_label_2.setObjectName("phase_label_2")
        self.gridLayout.addWidget(self.phase_label_2, 0, 0, 1, 1)
        self.tds_phase_spinbox = QtWidgets.QDoubleSpinBox(tds_control_panel)
        self.tds_phase_spinbox.setMinimum(-1080.0)
        self.tds_phase_spinbox.setMaximum(1080.0)
        self.tds_phase_spinbox.setObjectName("tds_phase_spinbox")
        self.gridLayout.addWidget(self.tds_phase_spinbox, 0, 1, 1, 2)
        self.phase_rb_label = QtWidgets.QLabel(tds_control_panel)
        self.phase_rb_label.setObjectName("phase_rb_label")
        self.gridLayout.addWidget(self.phase_rb_label, 0, 3, 1, 1)
        self.tds_phase_readback_line = QtWidgets.QLineEdit(tds_control_panel)
        self.tds_phase_readback_line.setMaxLength(14)
        self.tds_phase_readback_line.setReadOnly(True)
        self.tds_phase_readback_line.setClearButtonEnabled(False)
        self.tds_phase_readback_line.setObjectName("tds_phase_readback_line")
        self.gridLayout.addWidget(self.tds_phase_readback_line, 0, 4, 1, 1)
        self.amplitude_label = QtWidgets.QLabel(tds_control_panel)
        self.amplitude_label.setObjectName("amplitude_label")
        self.gridLayout.addWidget(self.amplitude_label, 1, 0, 1, 1)
        self.tds_amplitude_spinbox = QtWidgets.QDoubleSpinBox(tds_control_panel)
        self.tds_amplitude_spinbox.setMaximum(100.0)
        self.tds_amplitude_spinbox.setObjectName("tds_amplitude_spinbox")
        self.gridLayout.addWidget(self.tds_amplitude_spinbox, 1, 1, 1, 2)
        self.amplitude_rb_label = QtWidgets.QLabel(tds_control_panel)
        self.amplitude_rb_label.setObjectName("amplitude_rb_label")
        self.gridLayout.addWidget(self.amplitude_rb_label, 1, 3, 1, 1)
        self.tds_amplitude_readback_line = QtWidgets.QLineEdit(tds_control_panel)
        self.tds_amplitude_readback_line.setMaxLength(14)
        self.tds_amplitude_readback_line.setReadOnly(True)
        self.tds_amplitude_readback_line.setObjectName("tds_amplitude_readback_line")
        self.gridLayout.addWidget(self.tds_amplitude_readback_line, 1, 4, 1, 1)
        self.voltage_label = QtWidgets.QLabel(tds_control_panel)
        self.voltage_label.setEnabled(False)
        self.voltage_label.setObjectName("voltage_label")
        self.gridLayout.addWidget(self.voltage_label, 2, 0, 1, 2)
        self.tds_voltage_spinbox = QtWidgets.QDoubleSpinBox(tds_control_panel)
        self.tds_voltage_spinbox.setEnabled(False)
        self.tds_voltage_spinbox.setObjectName("tds_voltage_spinbox")
        self.gridLayout.addWidget(self.tds_voltage_spinbox, 2, 2, 1, 2)
        self.tds_calibration_pushbutton = QtWidgets.QPushButton(tds_control_panel)
        self.tds_calibration_pushbutton.setObjectName("tds_calibration_pushbutton")
        self.gridLayout.addWidget(self.tds_calibration_pushbutton, 2, 4, 2, 1)
        self.streak = QtWidgets.QLabel(tds_control_panel)
        self.streak.setEnabled(False)
        self.streak.setObjectName("streak")
        self.gridLayout.addWidget(self.streak, 3, 0, 1, 1)
        self.streak_spinbox = QtWidgets.QDoubleSpinBox(tds_control_panel)
        self.streak_spinbox.setEnabled(False)
        self.streak_spinbox.setObjectName("streak_spinbox")
        self.gridLayout.addWidget(self.streak_spinbox, 3, 2, 1, 2)

        self.retranslateUi(tds_control_panel)
        QtCore.QMetaObject.connectSlotsByName(tds_control_panel)

    def retranslateUi(self, tds_control_panel):
        _translate = QtCore.QCoreApplication.translate
        tds_control_panel.setWindowTitle(_translate("tds_control_panel", "Form"))
        self.phase_label_2.setText(_translate("tds_control_panel", "Phase / °"))
        self.phase_rb_label.setText(_translate("tds_control_panel", "Phase RB"))
        self.amplitude_label.setText(_translate("tds_control_panel", "Ampl. / %"))
        self.amplitude_rb_label.setText(_translate("tds_control_panel", "Ampl. RB"))
        self.voltage_label.setText(_translate("tds_control_panel", "Voltage / MV"))
        self.tds_calibration_pushbutton.setText(_translate("tds_control_panel", "Calibration..."))
        self.streak.setText(_translate("tds_control_panel", "Streak"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tds_control_panel = QtWidgets.QWidget()
    ui = Ui_tds_control_panel()
    ui.setupUi(tds_control_panel)
    tds_control_panel.show()
    sys.exit(app.exec_())
