# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tdsmini.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tdsmini_panel(object):
    def setupUi(self, tdsmini_panel):
        tdsmini_panel.setObjectName("tdsmini_panel")
        tdsmini_panel.resize(380, 201)
        self.gridLayout = QtWidgets.QGridLayout(tdsmini_panel)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(tdsmini_panel)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.amplitude_spinner = QtWidgets.QDoubleSpinBox(tdsmini_panel)
        self.amplitude_spinner.setPrefix("")
        self.amplitude_spinner.setMaximum(100.0)
        self.amplitude_spinner.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.amplitude_spinner.setObjectName("amplitude_spinner")
        self.gridLayout.addWidget(self.amplitude_spinner, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(tdsmini_panel)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.amplitude_rb = QtWidgets.QLabel(tdsmini_panel)
        self.amplitude_rb.setText("")
        self.amplitude_rb.setObjectName("amplitude_rb")
        self.gridLayout.addWidget(self.amplitude_rb, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(tdsmini_panel)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.add_180_deg_button = QtWidgets.QPushButton(tdsmini_panel)
        self.add_180_deg_button.setObjectName("add_180_deg_button")
        self.gridLayout.addWidget(self.add_180_deg_button, 3, 0, 1, 1)
        self.sub_180_deg_button = QtWidgets.QPushButton(tdsmini_panel)
        self.sub_180_deg_button.setObjectName("sub_180_deg_button")
        self.gridLayout.addWidget(self.sub_180_deg_button, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(tdsmini_panel)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.phase_spinner = QtWidgets.QDoubleSpinBox(tdsmini_panel)
        self.phase_spinner.setMinimum(-1000.0)
        self.phase_spinner.setMaximum(1000.0)
        self.phase_spinner.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.phase_spinner.setObjectName("phase_spinner")
        self.gridLayout.addWidget(self.phase_spinner, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(tdsmini_panel)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.phase_rb = QtWidgets.QLabel(tdsmini_panel)
        self.phase_rb.setText("")
        self.phase_rb.setObjectName("phase_rb")
        self.gridLayout.addWidget(self.phase_rb, 5, 1, 1, 1)

        self.retranslateUi(tdsmini_panel)
        QtCore.QMetaObject.connectSlotsByName(tdsmini_panel)

    def retranslateUi(self, tdsmini_panel):
        _translate = QtCore.QCoreApplication.translate
        tdsmini_panel.setWindowTitle(_translate("tdsmini_panel", "Form"))
        self.label.setText(_translate("tdsmini_panel", "Amplitude SP"))
        self.amplitude_spinner.setSuffix(_translate("tdsmini_panel", "%"))
        self.label_2.setText(_translate("tdsmini_panel", "Amplitude RB"))
        self.add_180_deg_button.setText(_translate("tdsmini_panel", "+180°"))
        self.sub_180_deg_button.setText(_translate("tdsmini_panel", "-180°"))
        self.label_7.setText(_translate("tdsmini_panel", "Phase SP"))
        self.phase_spinner.setSuffix(_translate("tdsmini_panel", "°"))
        self.label_5.setText(_translate("tdsmini_panel", "Phase RB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tdsmini_panel = QtWidgets.QWidget()
    ui = Ui_tdsmini_panel()
    ui.setupUi(tdsmini_panel)
    tdsmini_panel.show()
    sys.exit(app.exec_())
