# -*- coding: utf-8 -*-
"""
Sergey Tomin

Script to collect tuning data
"""
import time
from esme.mint.machine import Machine
from esme.mint.snapshot import Snapshot


SNAPSHOT_TEMPL = Snapshot()
SNAPSHOT_TEMPL.sase_sections = []
SNAPSHOT_TEMPL.magnet_prefix = None


SNAPSHOT_TEMPL.add_alarm_channels("XFEL.DIAG/TOROID/TORA.60.I1/CHARGE.ALL", min=0.005, max=1.5)

SNAPSHOT_TEMPL.add_channel("XFEL.UTIL/BUNCH_PATTERN/CONTROL/BEAM_ALLOWED")

SNAPSHOT_TEMPL.add_orbit_section("I1", tol=0.1, track=False)
SNAPSHOT_TEMPL.add_orbit_section("I1D", tol=0.1, track=False)

SNAPSHOT_TEMPL.add_magnet_section("I1", tol=0.01, track=False)
SNAPSHOT_TEMPL.add_magnet_section("I1D", tol=0.01, track=False)

# add camera

#SNAPSHOT_TEMPL.add_image("XFEL.DIAG/CAMERA/OTRA.473.B2D/IMAGE_EXT_ZMQ", folder="./tds_images")
# solenoid
SNAPSHOT_TEMPL.add_channel("XFEL.MAGNETS/MAGNET.ML/SOLB.23.I1/CURRENT.SP")

# A1  XFEL.RF/LLRF.CONTROLLER/CTRL.A1.I1/SP.AMPL
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/VS.A1.I1/PHASE.SAMPLE", tol=0.02)
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/VS.A1.I1/AMPL.SAMPLE", tol=0.1)
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/CTRL.A1.I1/SP.PHASE")
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/CTRL.A1.I1/SP.AMPL")

# gun phase
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/VS.GUN.I1/PHASE.SAMPLE", tol=0.03)
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/CTRL.GUN.I1/SP.PHASE", tol=0.01)
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/CTRL.GUN.I1/SP.AMPL")
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/VS.GUN.I1/AMPL.SAMPLE")


# AH1
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/VS.AH1.I1/PHASE.SAMPLE", tol=0.03)
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/VS.AH1.I1/AMPL.SAMPLE", tol=0.1)
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/CTRL.AH1.I1/SP.PHASE")
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/CTRL.AH1.I1/SP.AMPL")

# charge

SNAPSHOT_TEMPL.add_channel("XFEL.FEEDBACK/FT1.LONGITUDINAL/MONITOR1/TARGET")
SNAPSHOT_TEMPL.add_channel("XFEL.DIAG/CHARGE.ML/TORA.25.I1/CHARGE.ALL")




#SNAPSHOT_TEMPL.add_channel("XFEL.RF/LINAC_ENERGY_MANAGER/XFEL/ENERGY.2", tol=5)

SNAPSHOT_TEMPL.add_channel("XFEL.DIAG/BEAM_ENERGY_MEASUREMENT/LH/ENERGY.ALL", tol=0.2)

SNAPSHOT_TEMPL.add_channel("XFEL.DIAG/BEAM_ENERGY_MEASUREMENT/I1D/ENERGY.ALL", tol=0.2)


#BCs
SNAPSHOT_TEMPL.add_channel("XFEL.MAGNETS/CHICANE/LH/ANGLE")#mrad
SNAPSHOT_TEMPL.add_channel("XFEL.MAGNETS/CHICANE/BC0/ANGLE")
SNAPSHOT_TEMPL.add_channel("XFEL.MAGNETS/CHICANE/BC1/ANGLE")
SNAPSHOT_TEMPL.add_channel("XFEL.MAGNETS/CHICANE/BC2/ANGLE")

#Laser Heater
SNAPSHOT_TEMPL.add_channel("XFEL.UTIL/LASERHEATER.MOTOR/P1X.LHOS0/FPOS") #Laser position x compare with BPM.48 and .52
SNAPSHOT_TEMPL.add_channel("XFEL.UTIL/LASERHEATER.MOTOR/P1Z.LHOS0/FPOS") #Laser position y
SNAPSHOT_TEMPL.add_channel("XFEL.UTIL/LASERHEATER.MOTOR/LAMBDA2.LHOS0/POS") #laser intensity, min at 0 max at 7000
SNAPSHOT_TEMPL.add_channel("XFEL.UTIL/LASERHEATER.MOTOR/DL.LHLVL5/FPOS") #delay line, on beam at -241
SNAPSHOT_TEMPL.add_channel("XFEL.UTIL/LASERINT/GUN/SH3_OPEN") # UG5 shutter open
SNAPSHOT_TEMPL.add_channel("XFEL.UTIL/LASERINT/GUN/SH4_OPEN") # UG7 shutter open
# SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/CTRL.LLTDSB2/SP.PHASE")

# TDS injector
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/VS.LLTDSI1/AMPL.SAMPLE")
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/CTRL.LLTDSI1/SP.AMPL")
SNAPSHOT_TEMPL.add_channel("XFEL.RF/LLRF.CONTROLLER/CTRL.LLTDSI1/SP.PHASE")
SNAPSHOT_TEMPL.add_channel("XFEL.DIAG/TIMER.CENTRAL/MASTER/EVENT10")  # indication if TDS is on beam


# BAM
#SNAPSHOT_TEMPL.add_channel("XFEL.SDIAG/BAM/47.I1/LOW_CHARGE.RESOLUTION")
#SNAPSHOT_TEMPL.add_channel("XFEL.SDIAG/BAM/47.I1/LOW_CHARGE_SINGLEBUNCH_ARRIVAL_TIME.1")
#SNAPSHOT_TEMPL.add_channel("XFEL.SDIAG/BAM/47.I1/LOW_CHARGE_SINGLEBUNCH_ARRIVAL_TIME.2")
#SNAPSHOT_TEMPL.add_channel("XFEL.SDIAG/BAM/47.I1/LOW_CHARGE_SINGLEBUNCH_ARRIVAL_TIME.3")
